// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.12.4
// source: component_conf.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReaderOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Channel          *string     `protobuf:"bytes,1,opt,name=channel" json:"channel,omitempty"`
	QosProfile       *QosProfile `protobuf:"bytes,2,opt,name=qos_profile,json=qosProfile" json:"qos_profile,omitempty"`                            // depth: used to define capacity of processed messages
	PendingQueueSize *uint32     `protobuf:"varint,3,opt,name=pending_queue_size,json=pendingQueueSize,def=1" json:"pending_queue_size,omitempty"` // used to define capacity of unprocessed messages
}

// Default values for ReaderOption fields.
const (
	Default_ReaderOption_PendingQueueSize = uint32(1)
)

func (x *ReaderOption) Reset() {
	*x = ReaderOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_component_conf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReaderOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReaderOption) ProtoMessage() {}

func (x *ReaderOption) ProtoReflect() protoreflect.Message {
	mi := &file_component_conf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReaderOption.ProtoReflect.Descriptor instead.
func (*ReaderOption) Descriptor() ([]byte, []int) {
	return file_component_conf_proto_rawDescGZIP(), []int{0}
}

func (x *ReaderOption) GetChannel() string {
	if x != nil && x.Channel != nil {
		return *x.Channel
	}
	return ""
}

func (x *ReaderOption) GetQosProfile() *QosProfile {
	if x != nil {
		return x.QosProfile
	}
	return nil
}

func (x *ReaderOption) GetPendingQueueSize() uint32 {
	if x != nil && x.PendingQueueSize != nil {
		return *x.PendingQueueSize
	}
	return Default_ReaderOption_PendingQueueSize
}

type ComponentConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           *string         `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ConfigFilePath *string         `protobuf:"bytes,2,opt,name=config_file_path,json=configFilePath" json:"config_file_path,omitempty"`
	FlagFilePath   *string         `protobuf:"bytes,3,opt,name=flag_file_path,json=flagFilePath" json:"flag_file_path,omitempty"`
	Readers        []*ReaderOption `protobuf:"bytes,4,rep,name=readers" json:"readers,omitempty"`
}

func (x *ComponentConfig) Reset() {
	*x = ComponentConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_component_conf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComponentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentConfig) ProtoMessage() {}

func (x *ComponentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_component_conf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentConfig.ProtoReflect.Descriptor instead.
func (*ComponentConfig) Descriptor() ([]byte, []int) {
	return file_component_conf_proto_rawDescGZIP(), []int{1}
}

func (x *ComponentConfig) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ComponentConfig) GetConfigFilePath() string {
	if x != nil && x.ConfigFilePath != nil {
		return *x.ConfigFilePath
	}
	return ""
}

func (x *ComponentConfig) GetFlagFilePath() string {
	if x != nil && x.FlagFilePath != nil {
		return *x.FlagFilePath
	}
	return ""
}

func (x *ComponentConfig) GetReaders() []*ReaderOption {
	if x != nil {
		return x.Readers
	}
	return nil
}

type TimerComponentConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	ConfigFilePath *string `protobuf:"bytes,2,opt,name=config_file_path,json=configFilePath" json:"config_file_path,omitempty"`
	FlagFilePath   *string `protobuf:"bytes,3,opt,name=flag_file_path,json=flagFilePath" json:"flag_file_path,omitempty"`
	Interval       *uint32 `protobuf:"varint,4,opt,name=interval" json:"interval,omitempty"` // In milliseconds.
}

func (x *TimerComponentConfig) Reset() {
	*x = TimerComponentConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_component_conf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimerComponentConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerComponentConfig) ProtoMessage() {}

func (x *TimerComponentConfig) ProtoReflect() protoreflect.Message {
	mi := &file_component_conf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerComponentConfig.ProtoReflect.Descriptor instead.
func (*TimerComponentConfig) Descriptor() ([]byte, []int) {
	return file_component_conf_proto_rawDescGZIP(), []int{2}
}

func (x *TimerComponentConfig) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *TimerComponentConfig) GetConfigFilePath() string {
	if x != nil && x.ConfigFilePath != nil {
		return *x.ConfigFilePath
	}
	return ""
}

func (x *TimerComponentConfig) GetFlagFilePath() string {
	if x != nil && x.FlagFilePath != nil {
		return *x.FlagFilePath
	}
	return ""
}

func (x *TimerComponentConfig) GetInterval() uint32 {
	if x != nil && x.Interval != nil {
		return *x.Interval
	}
	return 0
}

var File_component_conf_proto protoreflect.FileDescriptor

var file_component_conf_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x63,
	0x79, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x71, 0x6f, 0x73, 0x5f,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9a, 0x01,
	0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x3f, 0x0a, 0x0b, 0x71, 0x6f, 0x73, 0x5f,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x51, 0x6f, 0x73, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x0a, 0x71,
	0x6f, 0x73, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x2f, 0x0a, 0x12, 0x70, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x3a, 0x01, 0x31, 0x52, 0x10, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x51, 0x75, 0x65, 0x75, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xb1, 0x01, 0x0a, 0x0f, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x66, 0x69, 0x6c,
	0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x24, 0x0a, 0x0e,
	0x66, 0x6c, 0x61, 0x67, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x6c, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61,
	0x74, 0x68, 0x12, 0x3a, 0x0a, 0x07, 0x72, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x63, 0x79, 0x62,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x65, 0x72, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x72, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x22, 0x96,
	0x01, 0x0a, 0x14, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x46, 0x69, 0x6c,
	0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x24, 0x0a, 0x0e, 0x66, 0x6c, 0x61, 0x67, 0x5f, 0x66, 0x69,
	0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66,
	0x6c, 0x61, 0x67, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
}

var (
	file_component_conf_proto_rawDescOnce sync.Once
	file_component_conf_proto_rawDescData = file_component_conf_proto_rawDesc
)

func file_component_conf_proto_rawDescGZIP() []byte {
	file_component_conf_proto_rawDescOnce.Do(func() {
		file_component_conf_proto_rawDescData = protoimpl.X.CompressGZIP(file_component_conf_proto_rawDescData)
	})
	return file_component_conf_proto_rawDescData
}

var file_component_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_component_conf_proto_goTypes = []interface{}{
	(*ReaderOption)(nil),         // 0: apollo.cyber.proto.ReaderOption
	(*ComponentConfig)(nil),      // 1: apollo.cyber.proto.ComponentConfig
	(*TimerComponentConfig)(nil), // 2: apollo.cyber.proto.TimerComponentConfig
	(*QosProfile)(nil),           // 3: apollo.cyber.proto.QosProfile
}
var file_component_conf_proto_depIdxs = []int32{
	3, // 0: apollo.cyber.proto.ReaderOption.qos_profile:type_name -> apollo.cyber.proto.QosProfile
	0, // 1: apollo.cyber.proto.ComponentConfig.readers:type_name -> apollo.cyber.proto.ReaderOption
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_component_conf_proto_init() }
func file_component_conf_proto_init() {
	if File_component_conf_proto != nil {
		return
	}
	file_qos_profile_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_component_conf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReaderOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_component_conf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComponentConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_component_conf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimerComponentConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_component_conf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_component_conf_proto_goTypes,
		DependencyIndexes: file_component_conf_proto_depIdxs,
		MessageInfos:      file_component_conf_proto_msgTypes,
	}.Build()
	File_component_conf_proto = out.File
	file_component_conf_proto_rawDesc = nil
	file_component_conf_proto_goTypes = nil
	file_component_conf_proto_depIdxs = nil
}
