// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.12.4
// source: dag_conf.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComponentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassName *string          `protobuf:"bytes,1,opt,name=class_name,json=className" json:"class_name,omitempty"`
	Config    *ComponentConfig `protobuf:"bytes,2,opt,name=config" json:"config,omitempty"`
}

func (x *ComponentInfo) Reset() {
	*x = ComponentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_conf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComponentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentInfo) ProtoMessage() {}

func (x *ComponentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dag_conf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentInfo.ProtoReflect.Descriptor instead.
func (*ComponentInfo) Descriptor() ([]byte, []int) {
	return file_dag_conf_proto_rawDescGZIP(), []int{0}
}

func (x *ComponentInfo) GetClassName() string {
	if x != nil && x.ClassName != nil {
		return *x.ClassName
	}
	return ""
}

func (x *ComponentInfo) GetConfig() *ComponentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type TimerComponentInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassName *string               `protobuf:"bytes,1,opt,name=class_name,json=className" json:"class_name,omitempty"`
	Config    *TimerComponentConfig `protobuf:"bytes,2,opt,name=config" json:"config,omitempty"`
}

func (x *TimerComponentInfo) Reset() {
	*x = TimerComponentInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_conf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimerComponentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerComponentInfo) ProtoMessage() {}

func (x *TimerComponentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_dag_conf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerComponentInfo.ProtoReflect.Descriptor instead.
func (*TimerComponentInfo) Descriptor() ([]byte, []int) {
	return file_dag_conf_proto_rawDescGZIP(), []int{1}
}

func (x *TimerComponentInfo) GetClassName() string {
	if x != nil && x.ClassName != nil {
		return *x.ClassName
	}
	return ""
}

func (x *TimerComponentInfo) GetConfig() *TimerComponentConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ModuleConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleLibrary   *string               `protobuf:"bytes,1,opt,name=module_library,json=moduleLibrary" json:"module_library,omitempty"`
	Components      []*ComponentInfo      `protobuf:"bytes,2,rep,name=components" json:"components,omitempty"`
	TimerComponents []*TimerComponentInfo `protobuf:"bytes,3,rep,name=timer_components,json=timerComponents" json:"timer_components,omitempty"`
}

func (x *ModuleConfig) Reset() {
	*x = ModuleConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_conf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleConfig) ProtoMessage() {}

func (x *ModuleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_dag_conf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleConfig.ProtoReflect.Descriptor instead.
func (*ModuleConfig) Descriptor() ([]byte, []int) {
	return file_dag_conf_proto_rawDescGZIP(), []int{2}
}

func (x *ModuleConfig) GetModuleLibrary() string {
	if x != nil && x.ModuleLibrary != nil {
		return *x.ModuleLibrary
	}
	return ""
}

func (x *ModuleConfig) GetComponents() []*ComponentInfo {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *ModuleConfig) GetTimerComponents() []*TimerComponentInfo {
	if x != nil {
		return x.TimerComponents
	}
	return nil
}

type DagConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ModuleConfig []*ModuleConfig `protobuf:"bytes,1,rep,name=module_config,json=moduleConfig" json:"module_config,omitempty"`
}

func (x *DagConfig) Reset() {
	*x = DagConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dag_conf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DagConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DagConfig) ProtoMessage() {}

func (x *DagConfig) ProtoReflect() protoreflect.Message {
	mi := &file_dag_conf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DagConfig.ProtoReflect.Descriptor instead.
func (*DagConfig) Descriptor() ([]byte, []int) {
	return file_dag_conf_proto_rawDescGZIP(), []int{3}
}

func (x *DagConfig) GetModuleConfig() []*ModuleConfig {
	if x != nil {
		return x.ModuleConfig
	}
	return nil
}

var File_dag_conf_proto protoreflect.FileDescriptor

var file_dag_conf_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x61, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x12, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5f,
	0x63, 0x6f, 0x6e, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x0d, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x6f,
	0x6c, 0x6c, 0x6f, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x75, 0x0a, 0x12, 0x54, 0x69, 0x6d, 0x65, 0x72,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x40, 0x0a, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61,
	0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0xcb,
	0x01, 0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x25, 0x0a, 0x0e, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4c,
	0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x12, 0x41, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x6f,
	0x6c, 0x6c, 0x6f, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x51, 0x0a, 0x10, 0x74, 0x69, 0x6d,
	0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x63, 0x79, 0x62,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x72, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x74, 0x69, 0x6d,
	0x65, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x52, 0x0a, 0x09,
	0x44, 0x61, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x45, 0x0a, 0x0d, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x20, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x0c, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
}

var (
	file_dag_conf_proto_rawDescOnce sync.Once
	file_dag_conf_proto_rawDescData = file_dag_conf_proto_rawDesc
)

func file_dag_conf_proto_rawDescGZIP() []byte {
	file_dag_conf_proto_rawDescOnce.Do(func() {
		file_dag_conf_proto_rawDescData = protoimpl.X.CompressGZIP(file_dag_conf_proto_rawDescData)
	})
	return file_dag_conf_proto_rawDescData
}

var file_dag_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dag_conf_proto_goTypes = []interface{}{
	(*ComponentInfo)(nil),        // 0: apollo.cyber.proto.ComponentInfo
	(*TimerComponentInfo)(nil),   // 1: apollo.cyber.proto.TimerComponentInfo
	(*ModuleConfig)(nil),         // 2: apollo.cyber.proto.ModuleConfig
	(*DagConfig)(nil),            // 3: apollo.cyber.proto.DagConfig
	(*ComponentConfig)(nil),      // 4: apollo.cyber.proto.ComponentConfig
	(*TimerComponentConfig)(nil), // 5: apollo.cyber.proto.TimerComponentConfig
}
var file_dag_conf_proto_depIdxs = []int32{
	4, // 0: apollo.cyber.proto.ComponentInfo.config:type_name -> apollo.cyber.proto.ComponentConfig
	5, // 1: apollo.cyber.proto.TimerComponentInfo.config:type_name -> apollo.cyber.proto.TimerComponentConfig
	0, // 2: apollo.cyber.proto.ModuleConfig.components:type_name -> apollo.cyber.proto.ComponentInfo
	1, // 3: apollo.cyber.proto.ModuleConfig.timer_components:type_name -> apollo.cyber.proto.TimerComponentInfo
	2, // 4: apollo.cyber.proto.DagConfig.module_config:type_name -> apollo.cyber.proto.ModuleConfig
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_dag_conf_proto_init() }
func file_dag_conf_proto_init() {
	if File_dag_conf_proto != nil {
		return
	}
	file_component_conf_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_dag_conf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComponentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_conf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimerComponentInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_conf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dag_conf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DagConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dag_conf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dag_conf_proto_goTypes,
		DependencyIndexes: file_dag_conf_proto_depIdxs,
		MessageInfos:      file_dag_conf_proto_msgTypes,
	}.Build()
	File_dag_conf_proto = out.File
	file_dag_conf_proto_rawDesc = nil
	file_dag_conf_proto_goTypes = nil
	file_dag_conf_proto_depIdxs = nil
}
