// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.12.4
// source: qos_profile.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QosHistoryPolicy int32

const (
	QosHistoryPolicy_HISTORY_SYSTEM_DEFAULT QosHistoryPolicy = 0
	QosHistoryPolicy_HISTORY_KEEP_LAST      QosHistoryPolicy = 1
	QosHistoryPolicy_HISTORY_KEEP_ALL       QosHistoryPolicy = 2
)

// Enum value maps for QosHistoryPolicy.
var (
	QosHistoryPolicy_name = map[int32]string{
		0: "HISTORY_SYSTEM_DEFAULT",
		1: "HISTORY_KEEP_LAST",
		2: "HISTORY_KEEP_ALL",
	}
	QosHistoryPolicy_value = map[string]int32{
		"HISTORY_SYSTEM_DEFAULT": 0,
		"HISTORY_KEEP_LAST":      1,
		"HISTORY_KEEP_ALL":       2,
	}
)

func (x QosHistoryPolicy) Enum() *QosHistoryPolicy {
	p := new(QosHistoryPolicy)
	*p = x
	return p
}

func (x QosHistoryPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QosHistoryPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_qos_profile_proto_enumTypes[0].Descriptor()
}

func (QosHistoryPolicy) Type() protoreflect.EnumType {
	return &file_qos_profile_proto_enumTypes[0]
}

func (x QosHistoryPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *QosHistoryPolicy) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = QosHistoryPolicy(num)
	return nil
}

// Deprecated: Use QosHistoryPolicy.Descriptor instead.
func (QosHistoryPolicy) EnumDescriptor() ([]byte, []int) {
	return file_qos_profile_proto_rawDescGZIP(), []int{0}
}

type QosReliabilityPolicy int32

const (
	QosReliabilityPolicy_RELIABILITY_SYSTEM_DEFAULT QosReliabilityPolicy = 0
	QosReliabilityPolicy_RELIABILITY_RELIABLE       QosReliabilityPolicy = 1
	QosReliabilityPolicy_RELIABILITY_BEST_EFFORT    QosReliabilityPolicy = 2
)

// Enum value maps for QosReliabilityPolicy.
var (
	QosReliabilityPolicy_name = map[int32]string{
		0: "RELIABILITY_SYSTEM_DEFAULT",
		1: "RELIABILITY_RELIABLE",
		2: "RELIABILITY_BEST_EFFORT",
	}
	QosReliabilityPolicy_value = map[string]int32{
		"RELIABILITY_SYSTEM_DEFAULT": 0,
		"RELIABILITY_RELIABLE":       1,
		"RELIABILITY_BEST_EFFORT":    2,
	}
)

func (x QosReliabilityPolicy) Enum() *QosReliabilityPolicy {
	p := new(QosReliabilityPolicy)
	*p = x
	return p
}

func (x QosReliabilityPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QosReliabilityPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_qos_profile_proto_enumTypes[1].Descriptor()
}

func (QosReliabilityPolicy) Type() protoreflect.EnumType {
	return &file_qos_profile_proto_enumTypes[1]
}

func (x QosReliabilityPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *QosReliabilityPolicy) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = QosReliabilityPolicy(num)
	return nil
}

// Deprecated: Use QosReliabilityPolicy.Descriptor instead.
func (QosReliabilityPolicy) EnumDescriptor() ([]byte, []int) {
	return file_qos_profile_proto_rawDescGZIP(), []int{1}
}

type QosDurabilityPolicy int32

const (
	QosDurabilityPolicy_DURABILITY_SYSTEM_DEFAULT  QosDurabilityPolicy = 0
	QosDurabilityPolicy_DURABILITY_TRANSIENT_LOCAL QosDurabilityPolicy = 1
	QosDurabilityPolicy_DURABILITY_VOLATILE        QosDurabilityPolicy = 2
)

// Enum value maps for QosDurabilityPolicy.
var (
	QosDurabilityPolicy_name = map[int32]string{
		0: "DURABILITY_SYSTEM_DEFAULT",
		1: "DURABILITY_TRANSIENT_LOCAL",
		2: "DURABILITY_VOLATILE",
	}
	QosDurabilityPolicy_value = map[string]int32{
		"DURABILITY_SYSTEM_DEFAULT":  0,
		"DURABILITY_TRANSIENT_LOCAL": 1,
		"DURABILITY_VOLATILE":        2,
	}
)

func (x QosDurabilityPolicy) Enum() *QosDurabilityPolicy {
	p := new(QosDurabilityPolicy)
	*p = x
	return p
}

func (x QosDurabilityPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QosDurabilityPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_qos_profile_proto_enumTypes[2].Descriptor()
}

func (QosDurabilityPolicy) Type() protoreflect.EnumType {
	return &file_qos_profile_proto_enumTypes[2]
}

func (x QosDurabilityPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *QosDurabilityPolicy) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = QosDurabilityPolicy(num)
	return nil
}

// Deprecated: Use QosDurabilityPolicy.Descriptor instead.
func (QosDurabilityPolicy) EnumDescriptor() ([]byte, []int) {
	return file_qos_profile_proto_rawDescGZIP(), []int{2}
}

type QosProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	History     *QosHistoryPolicy     `protobuf:"varint,1,opt,name=history,enum=apollo.cyber.proto.QosHistoryPolicy,def=1" json:"history,omitempty"`
	Depth       *uint32               `protobuf:"varint,2,opt,name=depth,def=1" json:"depth,omitempty"` // capacity of history
	Mps         *uint32               `protobuf:"varint,3,opt,name=mps,def=0" json:"mps,omitempty"`     // messages per second
	Reliability *QosReliabilityPolicy `protobuf:"varint,4,opt,name=reliability,enum=apollo.cyber.proto.QosReliabilityPolicy,def=1" json:"reliability,omitempty"`
	Durability  *QosDurabilityPolicy  `protobuf:"varint,5,opt,name=durability,enum=apollo.cyber.proto.QosDurabilityPolicy,def=2" json:"durability,omitempty"`
}

// Default values for QosProfile fields.
const (
	Default_QosProfile_History     = QosHistoryPolicy_HISTORY_KEEP_LAST
	Default_QosProfile_Depth       = uint32(1)
	Default_QosProfile_Mps         = uint32(0)
	Default_QosProfile_Reliability = QosReliabilityPolicy_RELIABILITY_RELIABLE
	Default_QosProfile_Durability  = QosDurabilityPolicy_DURABILITY_VOLATILE
)

func (x *QosProfile) Reset() {
	*x = QosProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_qos_profile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QosProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QosProfile) ProtoMessage() {}

func (x *QosProfile) ProtoReflect() protoreflect.Message {
	mi := &file_qos_profile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QosProfile.ProtoReflect.Descriptor instead.
func (*QosProfile) Descriptor() ([]byte, []int) {
	return file_qos_profile_proto_rawDescGZIP(), []int{0}
}

func (x *QosProfile) GetHistory() QosHistoryPolicy {
	if x != nil && x.History != nil {
		return *x.History
	}
	return Default_QosProfile_History
}

func (x *QosProfile) GetDepth() uint32 {
	if x != nil && x.Depth != nil {
		return *x.Depth
	}
	return Default_QosProfile_Depth
}

func (x *QosProfile) GetMps() uint32 {
	if x != nil && x.Mps != nil {
		return *x.Mps
	}
	return Default_QosProfile_Mps
}

func (x *QosProfile) GetReliability() QosReliabilityPolicy {
	if x != nil && x.Reliability != nil {
		return *x.Reliability
	}
	return Default_QosProfile_Reliability
}

func (x *QosProfile) GetDurability() QosDurabilityPolicy {
	if x != nil && x.Durability != nil {
		return *x.Durability
	}
	return Default_QosProfile_Durability
}

var File_qos_profile_proto protoreflect.FileDescriptor

var file_qos_profile_proto_rawDesc = []byte{
	0x0a, 0x11, 0x71, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x12, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x63, 0x79, 0x62, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcd, 0x02, 0x0a, 0x0a, 0x51, 0x6f, 0x73, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x51, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f,
	0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x6f, 0x73,
	0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x3a, 0x11, 0x48,
	0x49, 0x53, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x4b, 0x45, 0x45, 0x50, 0x5f, 0x4c, 0x41, 0x53, 0x54,
	0x52, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x17, 0x0a, 0x05, 0x64, 0x65, 0x70,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x3a, 0x01, 0x31, 0x52, 0x05, 0x64, 0x65, 0x70,
	0x74, 0x68, 0x12, 0x13, 0x0a, 0x03, 0x6d, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x3a,
	0x01, 0x30, 0x52, 0x03, 0x6d, 0x70, 0x73, 0x12, 0x60, 0x0a, 0x0b, 0x72, 0x65, 0x6c, 0x69, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x61,
	0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x51, 0x6f, 0x73, 0x52, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x3a, 0x14, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x49, 0x4c,
	0x49, 0x54, 0x59, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x52, 0x0b, 0x72, 0x65,
	0x6c, 0x69, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x5c, 0x0a, 0x0a, 0x64, 0x75, 0x72,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e,
	0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x51, 0x6f, 0x73, 0x44, 0x75, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x3a, 0x13, 0x44, 0x55, 0x52, 0x41, 0x42, 0x49, 0x4c, 0x49,
	0x54, 0x59, 0x5f, 0x56, 0x4f, 0x4c, 0x41, 0x54, 0x49, 0x4c, 0x45, 0x52, 0x0a, 0x64, 0x75, 0x72,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x2a, 0x5b, 0x0a, 0x10, 0x51, 0x6f, 0x73, 0x48, 0x69,
	0x73, 0x74, 0x6f, 0x72, 0x79, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x1a, 0x0a, 0x16, 0x48,
	0x49, 0x53, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f, 0x44, 0x45,
	0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x48, 0x49, 0x53, 0x54, 0x4f,
	0x52, 0x59, 0x5f, 0x4b, 0x45, 0x45, 0x50, 0x5f, 0x4c, 0x41, 0x53, 0x54, 0x10, 0x01, 0x12, 0x14,
	0x0a, 0x10, 0x48, 0x49, 0x53, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x4b, 0x45, 0x45, 0x50, 0x5f, 0x41,
	0x4c, 0x4c, 0x10, 0x02, 0x2a, 0x6d, 0x0a, 0x14, 0x51, 0x6f, 0x73, 0x52, 0x65, 0x6c, 0x69, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x1e, 0x0a, 0x1a,
	0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x53, 0x59, 0x53, 0x54,
	0x45, 0x4d, 0x5f, 0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14,
	0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x52, 0x45, 0x4c, 0x49,
	0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x1b, 0x0a, 0x17, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42,
	0x49, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x42, 0x45, 0x53, 0x54, 0x5f, 0x45, 0x46, 0x46, 0x4f, 0x52,
	0x54, 0x10, 0x02, 0x2a, 0x6d, 0x0a, 0x13, 0x51, 0x6f, 0x73, 0x44, 0x75, 0x72, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x79, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12, 0x1d, 0x0a, 0x19, 0x44, 0x55,
	0x52, 0x41, 0x42, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x5f,
	0x44, 0x45, 0x46, 0x41, 0x55, 0x4c, 0x54, 0x10, 0x00, 0x12, 0x1e, 0x0a, 0x1a, 0x44, 0x55, 0x52,
	0x41, 0x42, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x49, 0x45, 0x4e,
	0x54, 0x5f, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x44, 0x55, 0x52,
	0x41, 0x42, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x56, 0x4f, 0x4c, 0x41, 0x54, 0x49, 0x4c, 0x45,
	0x10, 0x02, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
}

var (
	file_qos_profile_proto_rawDescOnce sync.Once
	file_qos_profile_proto_rawDescData = file_qos_profile_proto_rawDesc
)

func file_qos_profile_proto_rawDescGZIP() []byte {
	file_qos_profile_proto_rawDescOnce.Do(func() {
		file_qos_profile_proto_rawDescData = protoimpl.X.CompressGZIP(file_qos_profile_proto_rawDescData)
	})
	return file_qos_profile_proto_rawDescData
}

var file_qos_profile_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_qos_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_qos_profile_proto_goTypes = []interface{}{
	(QosHistoryPolicy)(0),     // 0: apollo.cyber.proto.QosHistoryPolicy
	(QosReliabilityPolicy)(0), // 1: apollo.cyber.proto.QosReliabilityPolicy
	(QosDurabilityPolicy)(0),  // 2: apollo.cyber.proto.QosDurabilityPolicy
	(*QosProfile)(nil),        // 3: apollo.cyber.proto.QosProfile
}
var file_qos_profile_proto_depIdxs = []int32{
	0, // 0: apollo.cyber.proto.QosProfile.history:type_name -> apollo.cyber.proto.QosHistoryPolicy
	1, // 1: apollo.cyber.proto.QosProfile.reliability:type_name -> apollo.cyber.proto.QosReliabilityPolicy
	2, // 2: apollo.cyber.proto.QosProfile.durability:type_name -> apollo.cyber.proto.QosDurabilityPolicy
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_qos_profile_proto_init() }
func file_qos_profile_proto_init() {
	if File_qos_profile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_qos_profile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QosProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_qos_profile_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_qos_profile_proto_goTypes,
		DependencyIndexes: file_qos_profile_proto_depIdxs,
		EnumInfos:         file_qos_profile_proto_enumTypes,
		MessageInfos:      file_qos_profile_proto_msgTypes,
	}.Build()
	File_qos_profile_proto = out.File
	file_qos_profile_proto_rawDesc = nil
	file_qos_profile_proto_goTypes = nil
	file_qos_profile_proto_depIdxs = nil
}
