// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.12.4
// source: role_attributes.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SocketAddr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   *string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"` // dotted decimal
	Port *uint32 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (x *SocketAddr) Reset() {
	*x = SocketAddr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_attributes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SocketAddr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocketAddr) ProtoMessage() {}

func (x *SocketAddr) ProtoReflect() protoreflect.Message {
	mi := &file_role_attributes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocketAddr.ProtoReflect.Descriptor instead.
func (*SocketAddr) Descriptor() ([]byte, []int) {
	return file_role_attributes_proto_rawDescGZIP(), []int{0}
}

func (x *SocketAddr) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

func (x *SocketAddr) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

type RoleAttributes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HostName  *string `protobuf:"bytes,1,opt,name=host_name,json=hostName" json:"host_name,omitempty"`
	HostIp    *string `protobuf:"bytes,2,opt,name=host_ip,json=hostIp" json:"host_ip,omitempty"`
	ProcessId *int32  `protobuf:"varint,3,opt,name=process_id,json=processId" json:"process_id,omitempty"`
	NodeName  *string `protobuf:"bytes,4,opt,name=node_name,json=nodeName" json:"node_name,omitempty"`
	NodeId    *uint64 `protobuf:"varint,5,opt,name=node_id,json=nodeId" json:"node_id,omitempty"` // hash value of node_name
	// especially for WRITER and READER
	ChannelName *string     `protobuf:"bytes,6,opt,name=channel_name,json=channelName" json:"channel_name,omitempty"`
	ChannelId   *uint64     `protobuf:"varint,7,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"` // hash value of channel_name
	MessageType *string     `protobuf:"bytes,8,opt,name=message_type,json=messageType" json:"message_type,omitempty"`
	ProtoDesc   []byte      `protobuf:"bytes,9,opt,name=proto_desc,json=protoDesc" json:"proto_desc,omitempty"`
	Id          *uint64     `protobuf:"varint,10,opt,name=id" json:"id,omitempty"`
	QosProfile  *QosProfile `protobuf:"bytes,11,opt,name=qos_profile,json=qosProfile" json:"qos_profile,omitempty"`
	SocketAddr  *SocketAddr `protobuf:"bytes,12,opt,name=socket_addr,json=socketAddr" json:"socket_addr,omitempty"` // reserved for socket communication
	// especially for SERVER and CLIENT
	ServiceName *string `protobuf:"bytes,13,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	ServiceId   *uint64 `protobuf:"varint,14,opt,name=service_id,json=serviceId" json:"service_id,omitempty"` // hash value of service_name
}

func (x *RoleAttributes) Reset() {
	*x = RoleAttributes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_role_attributes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAttributes) ProtoMessage() {}

func (x *RoleAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_role_attributes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAttributes.ProtoReflect.Descriptor instead.
func (*RoleAttributes) Descriptor() ([]byte, []int) {
	return file_role_attributes_proto_rawDescGZIP(), []int{1}
}

func (x *RoleAttributes) GetHostName() string {
	if x != nil && x.HostName != nil {
		return *x.HostName
	}
	return ""
}

func (x *RoleAttributes) GetHostIp() string {
	if x != nil && x.HostIp != nil {
		return *x.HostIp
	}
	return ""
}

func (x *RoleAttributes) GetProcessId() int32 {
	if x != nil && x.ProcessId != nil {
		return *x.ProcessId
	}
	return 0
}

func (x *RoleAttributes) GetNodeName() string {
	if x != nil && x.NodeName != nil {
		return *x.NodeName
	}
	return ""
}

func (x *RoleAttributes) GetNodeId() uint64 {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return 0
}

func (x *RoleAttributes) GetChannelName() string {
	if x != nil && x.ChannelName != nil {
		return *x.ChannelName
	}
	return ""
}

func (x *RoleAttributes) GetChannelId() uint64 {
	if x != nil && x.ChannelId != nil {
		return *x.ChannelId
	}
	return 0
}

func (x *RoleAttributes) GetMessageType() string {
	if x != nil && x.MessageType != nil {
		return *x.MessageType
	}
	return ""
}

func (x *RoleAttributes) GetProtoDesc() []byte {
	if x != nil {
		return x.ProtoDesc
	}
	return nil
}

func (x *RoleAttributes) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *RoleAttributes) GetQosProfile() *QosProfile {
	if x != nil {
		return x.QosProfile
	}
	return nil
}

func (x *RoleAttributes) GetSocketAddr() *SocketAddr {
	if x != nil {
		return x.SocketAddr
	}
	return nil
}

func (x *RoleAttributes) GetServiceName() string {
	if x != nil && x.ServiceName != nil {
		return *x.ServiceName
	}
	return ""
}

func (x *RoleAttributes) GetServiceId() uint64 {
	if x != nil && x.ServiceId != nil {
		return *x.ServiceId
	}
	return 0
}

var File_role_attributes_proto protoreflect.FileDescriptor

var file_role_attributes_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e,
	0x63, 0x79, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x71, 0x6f, 0x73,
	0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30,
	0x0a, 0x0a, 0x53, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x22, 0xf3, 0x03, 0x0a, 0x0e, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x68, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x68, 0x6f, 0x73, 0x74, 0x49, 0x70, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x64, 0x65, 0x73,
	0x63, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x44, 0x65,
	0x73, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x3f, 0x0a, 0x0b, 0x71, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f,
	0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x6f, 0x73,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x0a, 0x71, 0x6f, 0x73, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x12, 0x3f, 0x0a, 0x0b, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6c,
	0x6f, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6f,
	0x63, 0x6b, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x52, 0x0a, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x41, 0x64, 0x64, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
}

var (
	file_role_attributes_proto_rawDescOnce sync.Once
	file_role_attributes_proto_rawDescData = file_role_attributes_proto_rawDesc
)

func file_role_attributes_proto_rawDescGZIP() []byte {
	file_role_attributes_proto_rawDescOnce.Do(func() {
		file_role_attributes_proto_rawDescData = protoimpl.X.CompressGZIP(file_role_attributes_proto_rawDescData)
	})
	return file_role_attributes_proto_rawDescData
}

var file_role_attributes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_role_attributes_proto_goTypes = []interface{}{
	(*SocketAddr)(nil),     // 0: apollo.cyber.proto.SocketAddr
	(*RoleAttributes)(nil), // 1: apollo.cyber.proto.RoleAttributes
	(*QosProfile)(nil),     // 2: apollo.cyber.proto.QosProfile
}
var file_role_attributes_proto_depIdxs = []int32{
	2, // 0: apollo.cyber.proto.RoleAttributes.qos_profile:type_name -> apollo.cyber.proto.QosProfile
	0, // 1: apollo.cyber.proto.RoleAttributes.socket_addr:type_name -> apollo.cyber.proto.SocketAddr
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_role_attributes_proto_init() }
func file_role_attributes_proto_init() {
	if File_role_attributes_proto != nil {
		return
	}
	file_qos_profile_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_role_attributes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SocketAddr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_role_attributes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleAttributes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_role_attributes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_role_attributes_proto_goTypes,
		DependencyIndexes: file_role_attributes_proto_depIdxs,
		MessageInfos:      file_role_attributes_proto_msgTypes,
	}.Build()
	File_role_attributes_proto = out.File
	file_role_attributes_proto_rawDesc = nil
	file_role_attributes_proto_goTypes = nil
	file_role_attributes_proto_depIdxs = nil
}
