// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.12.4
// source: run_mode_conf.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunMode int32

const (
	RunMode_MODE_REALITY    RunMode = 0
	RunMode_MODE_SIMULATION RunMode = 1
)

// Enum value maps for RunMode.
var (
	RunMode_name = map[int32]string{
		0: "MODE_REALITY",
		1: "MODE_SIMULATION",
	}
	RunMode_value = map[string]int32{
		"MODE_REALITY":    0,
		"MODE_SIMULATION": 1,
	}
)

func (x RunMode) Enum() *RunMode {
	p := new(RunMode)
	*p = x
	return p
}

func (x RunMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunMode) Descriptor() protoreflect.EnumDescriptor {
	return file_run_mode_conf_proto_enumTypes[0].Descriptor()
}

func (RunMode) Type() protoreflect.EnumType {
	return &file_run_mode_conf_proto_enumTypes[0]
}

func (x RunMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RunMode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RunMode(num)
	return nil
}

// Deprecated: Use RunMode.Descriptor instead.
func (RunMode) EnumDescriptor() ([]byte, []int) {
	return file_run_mode_conf_proto_rawDescGZIP(), []int{0}
}

type ClockMode int32

const (
	ClockMode_MODE_CYBER ClockMode = 0
	ClockMode_MODE_MOCK  ClockMode = 1
)

// Enum value maps for ClockMode.
var (
	ClockMode_name = map[int32]string{
		0: "MODE_CYBER",
		1: "MODE_MOCK",
	}
	ClockMode_value = map[string]int32{
		"MODE_CYBER": 0,
		"MODE_MOCK":  1,
	}
)

func (x ClockMode) Enum() *ClockMode {
	p := new(ClockMode)
	*p = x
	return p
}

func (x ClockMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClockMode) Descriptor() protoreflect.EnumDescriptor {
	return file_run_mode_conf_proto_enumTypes[1].Descriptor()
}

func (ClockMode) Type() protoreflect.EnumType {
	return &file_run_mode_conf_proto_enumTypes[1]
}

func (x ClockMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ClockMode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ClockMode(num)
	return nil
}

// Deprecated: Use ClockMode.Descriptor instead.
func (ClockMode) EnumDescriptor() ([]byte, []int) {
	return file_run_mode_conf_proto_rawDescGZIP(), []int{1}
}

type RunModeConf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunMode   *RunMode   `protobuf:"varint,1,opt,name=run_mode,json=runMode,enum=apollo.cyber.proto.RunMode,def=0" json:"run_mode,omitempty"`
	ClockMode *ClockMode `protobuf:"varint,2,opt,name=clock_mode,json=clockMode,enum=apollo.cyber.proto.ClockMode,def=0" json:"clock_mode,omitempty"`
}

// Default values for RunModeConf fields.
const (
	Default_RunModeConf_RunMode   = RunMode_MODE_REALITY
	Default_RunModeConf_ClockMode = ClockMode_MODE_CYBER
)

func (x *RunModeConf) Reset() {
	*x = RunModeConf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_run_mode_conf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunModeConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunModeConf) ProtoMessage() {}

func (x *RunModeConf) ProtoReflect() protoreflect.Message {
	mi := &file_run_mode_conf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunModeConf.ProtoReflect.Descriptor instead.
func (*RunModeConf) Descriptor() ([]byte, []int) {
	return file_run_mode_conf_proto_rawDescGZIP(), []int{0}
}

func (x *RunModeConf) GetRunMode() RunMode {
	if x != nil && x.RunMode != nil {
		return *x.RunMode
	}
	return Default_RunModeConf_RunMode
}

func (x *RunModeConf) GetClockMode() ClockMode {
	if x != nil && x.ClockMode != nil {
		return *x.ClockMode
	}
	return Default_RunModeConf_ClockMode
}

var File_run_mode_conf_proto protoreflect.FileDescriptor

var file_run_mode_conf_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x75, 0x6e, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x63, 0x79,
	0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9d, 0x01, 0x0a, 0x0b, 0x52, 0x75,
	0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x44, 0x0a, 0x08, 0x72, 0x75, 0x6e,
	0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x61, 0x70,
	0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x75, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x3a, 0x0c, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x52,
	0x45, 0x41, 0x4c, 0x49, 0x54, 0x59, 0x52, 0x07, 0x72, 0x75, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x12,
	0x48, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x63, 0x79, 0x62,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x6f,
	0x64, 0x65, 0x3a, 0x0a, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x43, 0x59, 0x42, 0x45, 0x52, 0x52, 0x09,
	0x63, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x2a, 0x30, 0x0a, 0x07, 0x52, 0x75, 0x6e,
	0x4d, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x52, 0x45, 0x41,
	0x4c, 0x49, 0x54, 0x59, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x53,
	0x49, 0x4d, 0x55, 0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x2a, 0x2a, 0x0a, 0x09, 0x43,
	0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x4d, 0x4f, 0x44, 0x45,
	0x5f, 0x43, 0x59, 0x42, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4d, 0x4f, 0x44, 0x45,
	0x5f, 0x4d, 0x4f, 0x43, 0x4b, 0x10, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
}

var (
	file_run_mode_conf_proto_rawDescOnce sync.Once
	file_run_mode_conf_proto_rawDescData = file_run_mode_conf_proto_rawDesc
)

func file_run_mode_conf_proto_rawDescGZIP() []byte {
	file_run_mode_conf_proto_rawDescOnce.Do(func() {
		file_run_mode_conf_proto_rawDescData = protoimpl.X.CompressGZIP(file_run_mode_conf_proto_rawDescData)
	})
	return file_run_mode_conf_proto_rawDescData
}

var file_run_mode_conf_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_run_mode_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_run_mode_conf_proto_goTypes = []interface{}{
	(RunMode)(0),        // 0: apollo.cyber.proto.RunMode
	(ClockMode)(0),      // 1: apollo.cyber.proto.ClockMode
	(*RunModeConf)(nil), // 2: apollo.cyber.proto.RunModeConf
}
var file_run_mode_conf_proto_depIdxs = []int32{
	0, // 0: apollo.cyber.proto.RunModeConf.run_mode:type_name -> apollo.cyber.proto.RunMode
	1, // 1: apollo.cyber.proto.RunModeConf.clock_mode:type_name -> apollo.cyber.proto.ClockMode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_run_mode_conf_proto_init() }
func file_run_mode_conf_proto_init() {
	if File_run_mode_conf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_run_mode_conf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunModeConf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_run_mode_conf_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_run_mode_conf_proto_goTypes,
		DependencyIndexes: file_run_mode_conf_proto_depIdxs,
		EnumInfos:         file_run_mode_conf_proto_enumTypes,
		MessageInfos:      file_run_mode_conf_proto_msgTypes,
	}.Build()
	File_run_mode_conf_proto = out.File
	file_run_mode_conf_proto_rawDesc = nil
	file_run_mode_conf_proto_goTypes = nil
	file_run_mode_conf_proto_depIdxs = nil
}
