// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.12.4
// source: topology_change.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChangeType int32

const (
	ChangeType_CHANGE_NODE        ChangeType = 1
	ChangeType_CHANGE_CHANNEL     ChangeType = 2
	ChangeType_CHANGE_SERVICE     ChangeType = 3
	ChangeType_CHANGE_PARTICIPANT ChangeType = 4
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		1: "CHANGE_NODE",
		2: "CHANGE_CHANNEL",
		3: "CHANGE_SERVICE",
		4: "CHANGE_PARTICIPANT",
	}
	ChangeType_value = map[string]int32{
		"CHANGE_NODE":        1,
		"CHANGE_CHANNEL":     2,
		"CHANGE_SERVICE":     3,
		"CHANGE_PARTICIPANT": 4,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_topology_change_proto_enumTypes[0].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_topology_change_proto_enumTypes[0]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ChangeType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ChangeType(num)
	return nil
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_topology_change_proto_rawDescGZIP(), []int{0}
}

type OperateType int32

const (
	OperateType_OPT_JOIN  OperateType = 1
	OperateType_OPT_LEAVE OperateType = 2
)

// Enum value maps for OperateType.
var (
	OperateType_name = map[int32]string{
		1: "OPT_JOIN",
		2: "OPT_LEAVE",
	}
	OperateType_value = map[string]int32{
		"OPT_JOIN":  1,
		"OPT_LEAVE": 2,
	}
)

func (x OperateType) Enum() *OperateType {
	p := new(OperateType)
	*p = x
	return p
}

func (x OperateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperateType) Descriptor() protoreflect.EnumDescriptor {
	return file_topology_change_proto_enumTypes[1].Descriptor()
}

func (OperateType) Type() protoreflect.EnumType {
	return &file_topology_change_proto_enumTypes[1]
}

func (x OperateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *OperateType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = OperateType(num)
	return nil
}

// Deprecated: Use OperateType.Descriptor instead.
func (OperateType) EnumDescriptor() ([]byte, []int) {
	return file_topology_change_proto_rawDescGZIP(), []int{1}
}

type RoleType int32

const (
	RoleType_ROLE_NODE        RoleType = 1
	RoleType_ROLE_WRITER      RoleType = 2
	RoleType_ROLE_READER      RoleType = 3
	RoleType_ROLE_SERVER      RoleType = 4
	RoleType_ROLE_CLIENT      RoleType = 5
	RoleType_ROLE_PARTICIPANT RoleType = 6
)

// Enum value maps for RoleType.
var (
	RoleType_name = map[int32]string{
		1: "ROLE_NODE",
		2: "ROLE_WRITER",
		3: "ROLE_READER",
		4: "ROLE_SERVER",
		5: "ROLE_CLIENT",
		6: "ROLE_PARTICIPANT",
	}
	RoleType_value = map[string]int32{
		"ROLE_NODE":        1,
		"ROLE_WRITER":      2,
		"ROLE_READER":      3,
		"ROLE_SERVER":      4,
		"ROLE_CLIENT":      5,
		"ROLE_PARTICIPANT": 6,
	}
)

func (x RoleType) Enum() *RoleType {
	p := new(RoleType)
	*p = x
	return p
}

func (x RoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_topology_change_proto_enumTypes[2].Descriptor()
}

func (RoleType) Type() protoreflect.EnumType {
	return &file_topology_change_proto_enumTypes[2]
}

func (x RoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RoleType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RoleType(num)
	return nil
}

// Deprecated: Use RoleType.Descriptor instead.
func (RoleType) EnumDescriptor() ([]byte, []int) {
	return file_topology_change_proto_rawDescGZIP(), []int{2}
}

type ChangeMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp   *uint64         `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	ChangeType  *ChangeType     `protobuf:"varint,2,opt,name=change_type,json=changeType,enum=apollo.cyber.proto.ChangeType" json:"change_type,omitempty"`
	OperateType *OperateType    `protobuf:"varint,3,opt,name=operate_type,json=operateType,enum=apollo.cyber.proto.OperateType" json:"operate_type,omitempty"`
	RoleType    *RoleType       `protobuf:"varint,4,opt,name=role_type,json=roleType,enum=apollo.cyber.proto.RoleType" json:"role_type,omitempty"`
	RoleAttr    *RoleAttributes `protobuf:"bytes,5,opt,name=role_attr,json=roleAttr" json:"role_attr,omitempty"`
}

func (x *ChangeMsg) Reset() {
	*x = ChangeMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_topology_change_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMsg) ProtoMessage() {}

func (x *ChangeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_topology_change_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMsg.ProtoReflect.Descriptor instead.
func (*ChangeMsg) Descriptor() ([]byte, []int) {
	return file_topology_change_proto_rawDescGZIP(), []int{0}
}

func (x *ChangeMsg) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *ChangeMsg) GetChangeType() ChangeType {
	if x != nil && x.ChangeType != nil {
		return *x.ChangeType
	}
	return ChangeType_CHANGE_NODE
}

func (x *ChangeMsg) GetOperateType() OperateType {
	if x != nil && x.OperateType != nil {
		return *x.OperateType
	}
	return OperateType_OPT_JOIN
}

func (x *ChangeMsg) GetRoleType() RoleType {
	if x != nil && x.RoleType != nil {
		return *x.RoleType
	}
	return RoleType_ROLE_NODE
}

func (x *ChangeMsg) GetRoleAttr() *RoleAttributes {
	if x != nil {
		return x.RoleAttr
	}
	return nil
}

var File_topology_change_proto protoreflect.FileDescriptor

var file_topology_change_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x6f, 0x70, 0x6f, 0x6c, 0x6f, 0x67, 0x79, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e,
	0x63, 0x79, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x72, 0x6f, 0x6c,
	0x65, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xaa, 0x02, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x73, 0x67,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x3f,
	0x0a, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x63, 0x79, 0x62,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x42, 0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x63,
	0x79, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e,
	0x63, 0x79, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3f,
	0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x73, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x41, 0x74, 0x74, 0x72, 0x2a,
	0x5d, 0x0a, 0x0a, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a,
	0x0b, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x4e, 0x4f, 0x44, 0x45, 0x10, 0x01, 0x12, 0x12,
	0x0a, 0x0e, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c,
	0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x53, 0x45, 0x52,
	0x56, 0x49, 0x43, 0x45, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45,
	0x5f, 0x50, 0x41, 0x52, 0x54, 0x49, 0x43, 0x49, 0x50, 0x41, 0x4e, 0x54, 0x10, 0x04, 0x2a, 0x2a,
	0x0a, 0x0b, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a,
	0x08, 0x4f, 0x50, 0x54, 0x5f, 0x4a, 0x4f, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4f,
	0x50, 0x54, 0x5f, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x10, 0x02, 0x2a, 0x73, 0x0a, 0x08, 0x52, 0x6f,
	0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x4e,
	0x4f, 0x44, 0x45, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x57, 0x52,
	0x49, 0x54, 0x45, 0x52, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x52,
	0x45, 0x41, 0x44, 0x45, 0x52, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x4f, 0x4c, 0x45, 0x5f,
	0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x4f, 0x4c, 0x45,
	0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x05, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x4f, 0x4c,
	0x45, 0x5f, 0x50, 0x41, 0x52, 0x54, 0x49, 0x43, 0x49, 0x50, 0x41, 0x4e, 0x54, 0x10, 0x06, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
}

var (
	file_topology_change_proto_rawDescOnce sync.Once
	file_topology_change_proto_rawDescData = file_topology_change_proto_rawDesc
)

func file_topology_change_proto_rawDescGZIP() []byte {
	file_topology_change_proto_rawDescOnce.Do(func() {
		file_topology_change_proto_rawDescData = protoimpl.X.CompressGZIP(file_topology_change_proto_rawDescData)
	})
	return file_topology_change_proto_rawDescData
}

var file_topology_change_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_topology_change_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_topology_change_proto_goTypes = []interface{}{
	(ChangeType)(0),        // 0: apollo.cyber.proto.ChangeType
	(OperateType)(0),       // 1: apollo.cyber.proto.OperateType
	(RoleType)(0),          // 2: apollo.cyber.proto.RoleType
	(*ChangeMsg)(nil),      // 3: apollo.cyber.proto.ChangeMsg
	(*RoleAttributes)(nil), // 4: apollo.cyber.proto.RoleAttributes
}
var file_topology_change_proto_depIdxs = []int32{
	0, // 0: apollo.cyber.proto.ChangeMsg.change_type:type_name -> apollo.cyber.proto.ChangeType
	1, // 1: apollo.cyber.proto.ChangeMsg.operate_type:type_name -> apollo.cyber.proto.OperateType
	2, // 2: apollo.cyber.proto.ChangeMsg.role_type:type_name -> apollo.cyber.proto.RoleType
	4, // 3: apollo.cyber.proto.ChangeMsg.role_attr:type_name -> apollo.cyber.proto.RoleAttributes
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_topology_change_proto_init() }
func file_topology_change_proto_init() {
	if File_topology_change_proto != nil {
		return
	}
	file_role_attributes_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_topology_change_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_topology_change_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_topology_change_proto_goTypes,
		DependencyIndexes: file_topology_change_proto_depIdxs,
		EnumInfos:         file_topology_change_proto_enumTypes,
		MessageInfos:      file_topology_change_proto_msgTypes,
	}.Build()
	File_topology_change_proto = out.File
	file_topology_change_proto_rawDesc = nil
	file_topology_change_proto_goTypes = nil
	file_topology_change_proto_depIdxs = nil
}
