// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.12.4
// source: unit_test.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnitTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassName *string `protobuf:"bytes,1,opt,name=class_name,json=className" json:"class_name,omitempty"`
	CaseName  *string `protobuf:"bytes,2,opt,name=case_name,json=caseName" json:"case_name,omitempty"`
}

func (x *UnitTest) Reset() {
	*x = UnitTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unit_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnitTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnitTest) ProtoMessage() {}

func (x *UnitTest) ProtoReflect() protoreflect.Message {
	mi := &file_unit_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnitTest.ProtoReflect.Descriptor instead.
func (*UnitTest) Descriptor() ([]byte, []int) {
	return file_unit_test_proto_rawDescGZIP(), []int{0}
}

func (x *UnitTest) GetClassName() string {
	if x != nil && x.ClassName != nil {
		return *x.ClassName
	}
	return ""
}

func (x *UnitTest) GetCaseName() string {
	if x != nil && x.CaseName != nil {
		return *x.CaseName
	}
	return ""
}

type Chatter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp      *uint64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	LidarTimestamp *uint64 `protobuf:"varint,2,opt,name=lidar_timestamp,json=lidarTimestamp" json:"lidar_timestamp,omitempty"`
	Seq            *uint64 `protobuf:"varint,3,opt,name=seq" json:"seq,omitempty"`
	Content        []byte  `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
}

func (x *Chatter) Reset() {
	*x = Chatter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unit_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chatter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chatter) ProtoMessage() {}

func (x *Chatter) ProtoReflect() protoreflect.Message {
	mi := &file_unit_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chatter.ProtoReflect.Descriptor instead.
func (*Chatter) Descriptor() ([]byte, []int) {
	return file_unit_test_proto_rawDescGZIP(), []int{1}
}

func (x *Chatter) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *Chatter) GetLidarTimestamp() uint64 {
	if x != nil && x.LidarTimestamp != nil {
		return *x.LidarTimestamp
	}
	return 0
}

func (x *Chatter) GetSeq() uint64 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *Chatter) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ChatterBenchmark struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stamp   *uint64 `protobuf:"varint,1,opt,name=stamp" json:"stamp,omitempty"`
	Seq     *uint64 `protobuf:"varint,2,opt,name=seq" json:"seq,omitempty"`
	Content *string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
}

func (x *ChatterBenchmark) Reset() {
	*x = ChatterBenchmark{}
	if protoimpl.UnsafeEnabled {
		mi := &file_unit_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatterBenchmark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatterBenchmark) ProtoMessage() {}

func (x *ChatterBenchmark) ProtoReflect() protoreflect.Message {
	mi := &file_unit_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatterBenchmark.ProtoReflect.Descriptor instead.
func (*ChatterBenchmark) Descriptor() ([]byte, []int) {
	return file_unit_test_proto_rawDescGZIP(), []int{2}
}

func (x *ChatterBenchmark) GetStamp() uint64 {
	if x != nil && x.Stamp != nil {
		return *x.Stamp
	}
	return 0
}

func (x *ChatterBenchmark) GetSeq() uint64 {
	if x != nil && x.Seq != nil {
		return *x.Seq
	}
	return 0
}

func (x *ChatterBenchmark) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

var File_unit_test_proto protoreflect.FileDescriptor

var file_unit_test_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x61, 0x70, 0x6f, 0x6c, 0x6c, 0x6f, 0x2e, 0x63, 0x79, 0x62, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x46, 0x0a, 0x08, 0x55, 0x6e, 0x69, 0x74, 0x54, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x7c, 0x0a,
	0x07, 0x43, 0x68, 0x61, 0x74, 0x74, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x27, 0x0a, 0x0f, 0x6c, 0x69, 0x64, 0x61, 0x72, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0e, 0x6c, 0x69, 0x64, 0x61, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x54, 0x0a, 0x10, 0x43,
	0x68, 0x61, 0x74, 0x74, 0x65, 0x72, 0x42, 0x65, 0x6e, 0x63, 0x68, 0x6d, 0x61, 0x72, 0x6b, 0x12,
	0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
}

var (
	file_unit_test_proto_rawDescOnce sync.Once
	file_unit_test_proto_rawDescData = file_unit_test_proto_rawDesc
)

func file_unit_test_proto_rawDescGZIP() []byte {
	file_unit_test_proto_rawDescOnce.Do(func() {
		file_unit_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_unit_test_proto_rawDescData)
	})
	return file_unit_test_proto_rawDescData
}

var file_unit_test_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_unit_test_proto_goTypes = []interface{}{
	(*UnitTest)(nil),         // 0: apollo.cyber.proto.UnitTest
	(*Chatter)(nil),          // 1: apollo.cyber.proto.Chatter
	(*ChatterBenchmark)(nil), // 2: apollo.cyber.proto.ChatterBenchmark
}
var file_unit_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_unit_test_proto_init() }
func file_unit_test_proto_init() {
	if File_unit_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_unit_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnitTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unit_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chatter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_unit_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatterBenchmark); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_unit_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_unit_test_proto_goTypes,
		DependencyIndexes: file_unit_test_proto_depIdxs,
		MessageInfos:      file_unit_test_proto_msgTypes,
	}.Build()
	File_unit_test_proto = out.File
	file_unit_test_proto_rawDesc = nil
	file_unit_test_proto_goTypes = nil
	file_unit_test_proto_depIdxs = nil
}
